name: digitalhisto
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=2.0.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - alsa-lib=1.2.10
  - anndata=0.10.5.post1
  - anndata2ri=1.3.1
  - aom=3.6.1
  - argcomplete=3.2.2
  - arpack=3.8.0
  - array-api-compat=1.4
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=23.2.0
  - aws-c-auth=0.7.4
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.3
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.13
  - aws-c-io=0.13.33
  - aws-c-mqtt=0.9.7
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.2
  - aws-sdk-cpp=1.10.57
  - binutils_impl_linux-64=2.40
  - bioconductor-affy=1.80.0
  - bioconductor-affyio=1.72.0
  - bioconductor-annotate=1.80.0
  - bioconductor-annotationdbi=1.64.1
  - bioconductor-apeglm=1.24.0
  - bioconductor-biobase=2.62.0
  - bioconductor-biocfilecache=2.10.1
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocparallel=1.36.0
  - bioconductor-biomart=2.58.0
  - bioconductor-biostrings=2.70.1
  - bioconductor-data-packages=20231203
  - bioconductor-delayedarray=0.28.0
  - bioconductor-deseq2=1.42.0
  - bioconductor-edger=4.0.16
  - bioconductor-genefilter=1.84.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-go.db=3.18.0
  - bioconductor-gosemsim=2.28.0
  - bioconductor-impute=1.76.0
  - bioconductor-iranges=2.36.0
  - bioconductor-keggrest=1.42.0
  - bioconductor-limma=3.58.1
  - bioconductor-mast=1.28.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-mlinterfaces=1.82.0
  - bioconductor-mscoreutils=1.14.1
  - bioconductor-msnbase=2.28.1
  - bioconductor-mzid=1.40.0
  - bioconductor-mzr=2.36.0
  - bioconductor-org.hs.eg.db=3.18.0
  - bioconductor-pcamethods=1.94.0
  - bioconductor-preprocesscore=1.64.0
  - bioconductor-proloc=1.42.0
  - bioconductor-protgenerics=1.34.0
  - bioconductor-rhdf5lib=1.24.0
  - bioconductor-rrvgo=1.14.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-sva=3.50.0
  - bioconductor-vsn=3.70.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - blas=1.0
  - blinker=1.7.0
  - blosc=1.21.5
  - bokeh=3.3.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - cairo=1.18.0
  - certifi=2025.4.26
  - cffi=1.16.0
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - curl=8.5.0
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dask-core=2023.12.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.0
  - decorator=5.1.1
  - dunamai=1.19.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2023.12.2
  - gast=0.4.0
  - gcc_impl_linux-64=13.2.0
  - gdk-pixbuf=2.42.10
  - get-annotations=0.1.2
  - get_version=3.5.5
  - gettext=0.21.1
  - gfortran_impl_linux-64=13.2.0
  - ghostscript=10.03.1
  - giflib=5.2.1
  - git=2.43.0
  - glib=2.78.3
  - glib-tools=2.78.3
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=2.26.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - graphviz=9.0.0
  - grpcio=1.54.3
  - gsl=2.7
  - gst-plugins-base=1.22.8
  - gstreamer=1.22.8
  - gstreamer-orc=0.4.39
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=13.2.0
  - h5py=3.9.0
  - harfbuzz=8.3.0
  - hdf4=4.2.15
  - hdf5=1.14.1
  - icu=73.2
  - idna=3.6
  - imagecodecs-lite=2019.12.3
  - imageio=2.33.1
  - imagemagick=7.1.1_21
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.19.0
  - jbig=2.1
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jq=1.5
  - jupyter_client=8.6.0
  - jupyter_core=5.7.0
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - kneed=0.8.5
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leidenalg=0.10.1
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.2
  - libavif16=1.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcups=2.3.3
  - libcurand=10.3.4.107
  - libcurl=8.5.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libde265=1.0.11
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexif=0.6.21
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=7.2.0
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgd=2.3.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libgpg-error=1.47
  - libgrpc=1.54.3
  - libgsf=1.14.51
  - libheif=1.16.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libmatio=1.5.23
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=3.21.12
  - librsvg=2.56.3
  - libsanitizer=13.2.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=255
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libvips=8.14.5
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.6.0
  - libxml2=2.11.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.40.1
  - locket=1.0.0
  - louvain=0.8.1
  - lz4-c=1.9.4
  - make=4.3
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.3
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - natsort=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.6
  - networkx=3.2
  - nlopt=2.7.1
  - nspr=4.35
  - nss=3.96
  - numba=0.57.1
  - numpy=1.24.4
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openssl=3.3.1
  - opt_einsum=3.3.0
  - packaging=23.2
  - pandas=2.0.3
  - pandoc=3.2.1
  - pango=1.50.14
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.5
  - pcre=8.45
  - pcre2=10.42
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - pixman=0.42.2
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - platformdirs=4.1.0
  - plotly=5.18.0
  - ply=3.11
  - pooch=1.8.0
  - poppler=23.10.0
  - poppler-data=0.4.12
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pynndescent=0.5.11
  - pyopenssl=23.3.0
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.4
  - python_abi=3.10
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyvips=2.2.1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - rav1e=0.6.6
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rpy2=3.5.11
  - rsa=4.9
  - s2n=1.3.54
  - scanpy=1.9.6
  - scikit-image=0.20.0
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - sed=4.8
  - session-info=1.0.0
  - setuptools=69.0.3
  - simplegeneric=0.8.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - stdlib-list=0.8.0
  - svt-av1=1.7.0
  - sympy=1.12
  - sysroot_linux-64=2.12
  - tbb=2021.11.0
  - tenacity=8.2.3
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.4.0
  - texttable=1.7.0
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.3
  - toolz=0.12.0
  - torchaudio=2.1.2
  - torchtriton=2.1.0
  - torchvision=0.16.2
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2023d
  - tzlocal=5.2
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - werkzeug=3.0.1
  - wheel=0.42.0
  - wrapt=1.14.1
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.40
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - yq=3.2.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==1.2.0
      - affine==2.4.0
      - alabaster==0.7.16
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - async-lru==2.0.4
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cca-zoo==2.5.0
      - cellpose==2.2.3
      - cfgv==3.4.0
      - chex==0.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - combat==0.3.3
      - contextlib2==21.6.0
      - defusedxml==0.7.1
      - dicomweb-client==0.59.1
      - distlib==0.3.8
      - dm-tree==0.1.8
      - docrep==0.3.2
      - docutils==0.20.1
      - etils==1.7.0
      - fasteners==0.19
      - fastjsonschema==2.20.0
      - fastremap==1.15.0
      - fiona==1.10.1
      - flask==3.0.0
      - flask-cors==4.0.0
      - flax==0.7.4
      - fqdn==1.5.1
      - geomloss==0.2.6
      - geopandas==1.0.1
      - glymur==0.12.8
      - google-auth-oauthlib==0.4.6
      - gputil==1.4.0
      - graphst==1.1.1
      - h11==0.14.0
      - hdbscan==0.8.40
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.26.5
      - identify==2.6.0
      - igraph==0.11.6
      - imagecodecs==2023.9.18
      - imagesize==1.4.1
      - importlib-resources==6.4.2
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jax==0.4.13
      - jaxlib==0.4.13
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab>=4.2.0,<4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.11
      - kaleido==0.2.1
      - keopscore==2.2.3
      - keras==2.11.0
      - libclang==18.1.1
      - lightning==2.1.4
      - lightning-utilities==0.11.6
      - lxml==5.3.0
      - mahotas==1.4.18
      - mantel==2.2.1
      - markdown-it-py==3.0.0
      - matplotlib-venn==0.11.10
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - msgpack==1.0.8
      - mudata==0.2.3
      - multipledispatch==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nodeenv==1.9.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numcodecs==0.13.0
      - numpyro==0.12.1
      - nvidia-nccl-cu12==2.25.1
      - omegaconf==2.3.0
      - opencv-python==4.8.0.76
      - opencv-python-headless==4.10.0.84
      - openslide-python==1.2.0
      - optax==0.2.1
      - orbax-checkpoint==0.5.16
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pdf2image==1.17.0
      - peft==0.14.0
      - pillow==10.1.0
      - pot==0.9.2
      - pre-commit==3.6.1
      - prometheus-client==0.20.0
      - protobuf==3.19.6
      - pybind11==2.13.6
      - pydicom==2.4.4
      - pykeops==2.2.3
      - pyogrio==0.9.0
      - pyproj==3.6.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-json-logger==2.0.7
      - pytorch-lightning==2.4.0
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - qudida==0.0.4
      - rasterio==1.3.11
      - referencing==0.35.1
      - regex==2024.11.6
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - roifile==2024.5.24
      - rpds-py==0.20.0
      - safetensors==0.4.4
      - scikit-network==0.33.1
      - scvi-tools==1.1.5
      - seaborn==0.13.0
      - send2trash==1.8.3
      - shapely==2.0.2
      - simpleitk==2.3.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - snuggs==1.4.7
      - soupsieve==2.6
      - sphinx==7.2.6
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starbars==2.0.1
      - stringdb==0.1.5
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorflow==2.11.1
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorly==0.8.1
      - tensorstore==0.1.60
      - terminado==0.18.1
      - tifffile==2023.12.9
      - timm==1.0.7
      - tinycss2==1.3.0
      - tokenizers==0.21.0
      - torchmetrics==1.4.0.post0
      - torchviz==0.0.3
      - transformers==4.47.0
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - virtualenv==20.26.3
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - wsidicom==0.17.0
      - xgboost==2.1.3
      - zarr==2.16.1