#
# SPDX-FileCopyrightText: Copyright Â© 2025 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Lisa Fournier <lisa.fournier@idiap.ch>
#
# SPDX-License-Identifier: Apache 2.0
#
dino:
  head_n_prototypes: 4096
  loss_weight: 1.0
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
  kde_loss_weight: 0.0
  kde_kappa: 0
ibot:
  head_n_prototypes: 4096
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  separate_head: false
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
crops:
  global_crops_scale:
  - 0.32
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224
  local_crops_size: 96
  use_ect: false
optim:
  epochs: 1
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.0005
  final_lr: 1e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 10
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
train:
  batch_size: 25
  data_path: ../../results/TNBC/compute_patches/invasive
  output_dir: ../../pretrained_models/extended_uni/TNBC
  embed_dim: 1024
  seed: 0
  num_workers: 4
  cache_dataset: true
  centering: centering
  test: false
  data_type: "hdf5"
wandb: false
student:
  train_strategy: explora
  arch: vit_large
  patch_size: 16
  drop_path_rate: 0.3
  layerscale: 1e-05
  drop_path_uniform: true
  pretrained_weights: uni
  ffn_layer: mlp
  block_chunks: 4
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  teacher_temp_start: 0.04
  teacher_temp_end: 0.03
cls_mean: false
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: NO_SHARD
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
skip_extended_pre_training: true
